version: '3.8'

services:
  tracker_db:
    image: postgres
    env_file:
    - ./.env

  tracker_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/backend/src
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - tracker_db
